### ISSUE TITLE
Enforcing PR message style

### ISSUE THREAD

**Issue by gskorokhod** [conjure-cp/conjure-oxide#869]
https://github.com/danieleades/deluxe/actions/runs/15510402730/workflow?pr=24

I just stumbled on a way to enforce the PR message convention (fix: <something> etc) in CI, should we want to do that!
The workflow file is very simple

```yml
name: Lint PR title

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - reopened

permissions:
  pull-requests: read

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
